name: Tester

on: 
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Test
              id: test
              uses: artifact-version
            - name: Show
              run: |
                echo "branch=${{steps.test.outputs.branch}}"
                echo "release=${{steps.test.output.release}}"